### ISSUE TITLE
项目运行报错

### ISSUE THREAD

**Issue by D1N910** [ATQQ/uni-app-template#1]
当我执行项目时，在执行`yarn serve`指令时，会生成新的vant文件
![image](https://user-images.githubusercontent.com/23202836/128678914-b3fd419d-e26c-4c5c-a196-1f594fb2d509.png)

然后代码运行就报错了
![image](https://user-images.githubusercontent.com/23202836/128678955-5c206b58-9eba-4397-b2db-d4d87e86d4a6.png)

**Comment by D1N910** [comment]
（1）vant这个是uni-app自动生成的，🤦‍♂️；
（2）自动生成的这个文件有语法错误，居然只用修改其中报错的地方的url前面加个逗号就行 🤦‍♂️
https://blog.csdn.net/qq_40544291/article/details/105196520

这个报错是 eslint 的报错吗？是不是可以屏蔽的

**Comment by ATQQ** [comment]
刚看到issue，害。。

**Comment by ATQQ** [comment]
> （1）vant这个是uni-app自动生成的，🤦‍♂️； （2）自动生成的这个文件有语法错误，居然只用修改其中报错的地方的url前面加个逗号就行 🤦‍♂️ https://blog.csdn.net/qq_40544291/article/details/105196520
> 
> 这个报错是 eslint 的报错吗？是不是可以屏蔽的

应该不是，就是编译报错

**Comment by ATQQ** [comment]
记个TODO，下来迭代一下模板
